---
driver:
  name: vagrant

driver_config:
   network:
   - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list: 
    - apt::default
    - smokeping_test::default
    attributes:
